In [5]:
print('a')

import numpy as np

a
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: C:\Users\Nerea\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [6]:
a = np.random.rand(2, 3, 5)
print(a)

[[[0.77952489 0.58060923 0.34412215 0.70022648 0.24178179]
  [0.62752668 0.72089667 0.65642636 0.15873692 0.03346094]
  [0.92726869 0.63154862 0.22355195 0.25572783 0.09607069]]

 [[0.57618216 0.72698543 0.32182847 0.32340117 0.64162911]
  [0.75563043 0.6745817  0.21621912 0.61208631 0.31898478]
  [0.31180295 0.2132075  0.37186012 0.46786396 0.23877848]]]


In [7]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
f"El tamaño de a es {a.size}"
f"El tamaño de b es {b.size}"


'El tamaño de b es 30'

In [9]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
c = b.transpose(1, 0, 2)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
d = a + c
print(d)

[[[1.18548902 1.71199764 1.21297731 1.72751298 1.29806674]
  [1.91255457 1.83044507 1.47278959 1.28779218 1.56109244]
  [1.61669768 1.59655864 1.04630734 1.80323008 1.85823365]]

 [[1.45949199 1.70675404 1.64536788 1.25415925 1.99799471]
  [1.38576315 1.40385639 1.47618234 1.04619196 1.85981546]
  [1.54924605 1.05881509 1.19439113 1.69699461 1.69749644]]]


In [ ]:
a

array([[[0.18548902, 0.71199764, 0.21297731, 0.72751298, 0.29806674],
        [0.91255457, 0.83044507, 0.47278959, 0.28779218, 0.56109244],
        [0.61669768, 0.59655864, 0.04630734, 0.80323008, 0.85823365]],

       [[0.45949199, 0.70675404, 0.64536788, 0.25415925, 0.99799471],
        [0.38576315, 0.40385639, 0.47618234, 0.04619196, 0.85981546],
        [0.54924605, 0.05881509, 0.19439113, 0.69699461, 0.69749644]]])

In [ ]:
e = a*c
e

array([[[0.18548902, 0.71199764, 0.21297731, 0.72751298, 0.29806674],
        [0.91255457, 0.83044507, 0.47278959, 0.28779218, 0.56109244],
        [0.61669768, 0.59655864, 0.04630734, 0.80323008, 0.85823365]],

       [[0.45949199, 0.70675404, 0.64536788, 0.25415925, 0.99799471],
        [0.38576315, 0.40385639, 0.47618234, 0.04619196, 0.85981546],
        [0.54924605, 0.05881509, 0.19439113, 0.69699461, 0.69749644]]])

In [ ]:
d

array([[[1.18548902, 1.71199764, 1.21297731, 1.72751298, 1.29806674],
        [1.91255457, 1.83044507, 1.47278959, 1.28779218, 1.56109244],
        [1.61669768, 1.59655864, 1.04630734, 1.80323008, 1.85823365]],

       [[1.45949199, 1.70675404, 1.64536788, 1.25415925, 1.99799471],
        [1.38576315, 1.40385639, 1.47618234, 1.04619196, 1.85981546],
        [1.54924605, 1.05881509, 1.19439113, 1.69699461, 1.69749644]]])

In [ ]:
f = np.empty((2, 3, 5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [ ]:
for l in range(d.shape[0]):
    for c in range(d.shape[1]):
        for dim in range(d.shape[2]):
            if d[l][c][dim] == d_max:
                f[l][c][dim] = 100
            elif d[l][c][dim] > d_mean and d[l][c][dim] < d_max:
                f[l][c][dim] = 75
            elif d[l][c][dim] == d_mean:
                f[l][c][dim] = 50
            elif d[l][c][dim] == d_min:
                f[l][c][dim] = 0
            else:
                f[l][c][dim] = 25
                

print(f)
print(d)



[[[ 25.  75.  25.  75.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  75.  75.  25. 100.]
  [ 25.  25.  25.   0.  75.]
  [ 75.  25.  25.  75.  75.]]]
[[[1.18548902 1.71199764 1.21297731 1.72751298 1.29806674]
  [1.91255457 1.83044507 1.47278959 1.28779218 1.56109244]
  [1.61669768 1.59655864 1.04630734 1.80323008 1.85823365]]

 [[1.45949199 1.70675404 1.64536788 1.25415925 1.99799471]
  [1.38576315 1.40385639 1.47618234 1.04619196 1.85981546]
  [1.54924605 1.05881509 1.19439113 1.69699461 1.69749644]]]


In [ ]:
a = str(f[1][2][2])
print(a)
type(a)

25.0


str

In [ ]:
g = d.astype(str)

g[(d==d_max)] = "E"
g[(d>d_min) & (d<d_mean)] = "D"
g[(d==d_mean)] = "C"
g[(d>d_mean) & (d<d_max)] = "B"
g[(d==d_min)] = "A"

print(g)

[[['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'B']
  ['B' 'B' 'D' 'B' 'B']]

 [['D' 'B' 'B' 'D' 'E']
  ['D' 'D' 'D' 'A' 'B']
  ['B' 'D' 'D' 'B' 'B']]]


In [ ]:
g = d.astype(str)

g[(d==d_max)] = "E"
g[(d>d_min) & (d<d_mean)] = "D"
g[(d==d_mean)] = "C"
g[(d>d_mean) & (d<d_max)] = "B"
g[(d==d_min)] = "A"

print(g)

NameError: name 'd' is not defined